import Providers from "./Providers";
import Navbar from "../components/Navbar";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import 'leaflet/dist/leaflet.css';



export const metadata = {
  title: "Trivo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="flex flex-col items-center w-full">
        <Toaster />
        <Providers>
          <div className="">{children}</div>
          <Navbar />
        </Providers>
      </body>
    </html>
  );
}
